<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('vehicles')->insert(
            array(
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 1,
                    'vehicle_number' => 'Ba 11 pa 1111',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '7',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '20000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 2,
                    'vehicle_number' => 'Ba 12 pa 1212',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '7',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '20000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 3,
                    'vehicle_number' => 'Ba 13 pa 1313',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '7',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '20000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 4,
                    'vehicle_number' => 'Ba 14 pa 1414',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '7',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '20000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 5,
                    'vehicle_number' => 'Ba 15 pa 1515',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '7',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '20000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 5,
                    'vehicle_number' => 'Ba 15 pa 1616',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '4',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '15000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 5,
                    'vehicle_number' => 'Ba 15 pa 1717',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '9',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '2000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 5,
                    'vehicle_number' => 'Ba 15 pa 1818',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '4',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '3000',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'vehicle_number' => 'Ba 15 pa 1919',
                    'make_year' => '2015',
                    'status' => 'active',
                ),
                array(
                    'rider_id' => 2,
                    'vehicle_type' => 1,
                    'model_id' => 5,
                    'vehicle_number' => 'Ba 15 pa 2020',
                    'fuel_type' => 'petrol',
                    'vehicle_year' => 2021,
                    'seat' => '8',
                    'vehicle_colour' => 'black',
                    'engine_number' => '232568956',
                    'chassis_number' => '5659',
                    'transmission' => 'auto',
                    'full_capacity' => '55',
                    'mileage' => '15',
                    'price' => '3400',
                    'insurance_issue_date' => '2020/5/12',
                    'insurance_expiry_date' => '2021/5/12',
                    'status' => 'active',
                    'availability' => 'available',
                )
            )
        );
    }
}
